[package]
name = "day4"
version = "0.1.0"
authors = ["Jakob Nordstrom <Jakob.Nordstrom@omegapoint.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
regex = "1.7"